read_tab <- \(name) readr::read_csv(file.path(table_dir, name), show_col_types = FALSE)

pct <- \(x, digits = 0) paste0(formatC(100 * x, format = "f", digits = digits), "\\%")
pts <- \(x) formatC(100 * x, format = "f", digits = 0)
count <- \(x) prettyNum(x, big.mark = ",")

digit_names <- c("Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine")

# Macro names may contain letters only.
macro_name <- function(x) {
  x |>
    stringr::str_replace_all("[0-9]", \(d) digit_names[as.integer(d) + 1]) |>
    stringr::str_replace_all("[^A-Za-z]", "")
}

write_macros <- function(values, path) {
  lines <- paste0("\\newcommand{\\", macro_name(names(values)), "}{", values, "}")
  if (anyDuplicated(macro_name(names(values)))) stop("Duplicate macro names")
  writeLines(c("% Generated by scripts/04_tables.R; do not edit.", lines), path)
}

latex_escape <- function(x) {
  x |>
    stringr::str_replace_all("\\\\", "\\\\textbackslash{}") |>
    stringr::str_replace_all("([&%$#_{}])", "\\\\\\1") |>
    stringr::str_replace_all("\"([^\"]*)\"", "``\\1''")
}

# A longtable carries its own caption and label so it can break across pages.
write_table <- function(data, path, align, header, caption = NULL, label = NULL) {
  body <- apply(data, 1, \(row) paste0(paste(row, collapse = " & "), " \\\\"))
  head <- paste0(paste(header, collapse = " & "), " \\\\")
  if (is.null(caption)) {
    lines <- c(
      paste0("\\begin{tabular}{", align, "}"),
      "\\toprule", head, "\\midrule", body, "\\bottomrule",
      "\\end{tabular}"
    )
  } else {
    lines <- c(
      paste0("\\begin{longtable}{", align, "}"),
      paste0("\\caption{", caption, "}\\label{", label, "}\\\\"),
      "\\toprule", head, "\\midrule", "\\endfirsthead",
      "\\toprule", head, "\\midrule", "\\endhead",
      "\\bottomrule", "\\endlastfoot",
      body,
      "\\end{longtable}"
    )
  }
  writeLines(lines, path)
}

save_evidence <- function(plot, name) {
  size <- figure_sizes[[name]]
  path <- file.path(figure_dir, name)
  width <- size[["width"]]
  height <- size[["height"]]
  ggplot2::ggsave(paste0(path, ".pdf"), plot, width = width, height = height)
  ggplot2::ggsave(paste0(path, ".png"), plot, width = width, height = height, dpi = figure_dpi)
}

# Point estimates and 95% intervals look the same in every figure.
geom_estimate <- function(...) {
  ggplot2::geom_pointrange(
    ggplot2::aes(xmin = lower, xmax = upper),
    shape = 16, size = 0.3, linewidth = 0.45, ...
  )
}

geom_zero <- function() ggplot2::geom_vline(xintercept = 0, colour = reference_colour, linewidth = 0.3)
