read_tab <- \(name) readr::read_csv(file.path("tabs", name), show_col_types = FALSE)

pct <- \(x, digits = 0) paste0(formatC(100 * x, format = "f", digits = digits), "\\%")
pts <- \(x) formatC(100 * x, format = "f", digits = 0)
count <- \(x) prettyNum(x, big.mark = ",")

digit_names <- c("Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine")

# Macro names may contain letters only.
macro_name <- function(x) {
  x |>
    stringr::str_replace_all("[0-9]", \(d) digit_names[as.integer(d) + 1]) |>
    stringr::str_replace_all("[^A-Za-z]", "")
}

write_macros <- function(values, path) {
  lines <- paste0("\\newcommand{\\", macro_name(names(values)), "}{", values, "}")
  if (anyDuplicated(macro_name(names(values)))) stop("Duplicate macro names")
  writeLines(c("% Generated by scripts/tables.R; do not edit.", lines), path)
}

latex_escape <- function(x) {
  x |>
    stringr::str_replace_all("\\\\", "\\\\textbackslash{}") |>
    stringr::str_replace_all("([&%$#_{}])", "\\\\\\1") |>
    stringr::str_replace_all("\"([^\"]*)\"", "``\\1''")
}

# A longtable carries its own caption and label so it can break across pages.
write_table <- function(data, path, align, header, caption = NULL, label = NULL) {
  body <- apply(data, 1, \(row) paste0(paste(row, collapse = " & "), " \\\\"))
  head <- paste0(paste(header, collapse = " & "), " \\\\")
  if (is.null(caption)) {
    lines <- c(
      paste0("\\begin{tabular}{", align, "}"),
      "\\toprule", head, "\\midrule", body, "\\bottomrule",
      "\\end{tabular}"
    )
  } else {
    lines <- c(
      paste0("\\begin{longtable}{", align, "}"),
      paste0("\\caption{", caption, "}\\label{", label, "}\\\\"),
      "\\toprule", head, "\\midrule", "\\endfirsthead",
      "\\toprule", head, "\\midrule", "\\endhead",
      "\\bottomrule", "\\endlastfoot",
      body,
      "\\end{longtable}"
    )
  }
  writeLines(lines, path)
}
